[project]
name = "my-ai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ous-Boji", email = "ouss.boji@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.8",
    "numpy>=1.26",
    "torch>=2.14.0",
    "jupyter>=1.0",
    "scikit-learn>=1.4"
]

[project.optional-dependencies]
torch = [
    "torch>=2.3",
    "torchvision>=0.18"
]

llm = [
    "anthropic>=0.39",
    "openai>=1.50"
]

[project.scripts]
my-ai-project = "my_ai_project:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
